FORMAT: 1A
# API Documentation

# Group UserUpgradeRequest

User upgrade requests

## Get all user upgrade requests [/v1/users/upgrade_requests]

### Return all requests [GET]

+ Request Get all requests (application/json)

    + Headers

            Accept: application/json

+ Response 200 (application/json)

    + Headers

            

    + Body

            [
            
            ]
