# config/chewy.yml
# separate environment configs
test:
  host: 'localhost:9200'
  prefix: 'test'
development:
  host: 'localhost:9200'
production:
  host: 'https://search-tenders-braincode-prod2-atgnxbdeynfs2yb3awipo3zt74.us-east-1.es.amazonaws.com:443'