# config/chewy.yml
# separate environment configs
test:
  host: 'localhost:9200'
  prefix: 'test'
development:
  host: 'localhost:9200'
production:
  host: 'https://search-tenders-braincode-production-qc44iet2spzgqo6z4jcm6fc7xa.us-east-1.es.amazonaws.com:443'