default: &default
  from: 'anton.rogachevskyi@braincode.xyz'
  domain: 'http://api.dev.tenderscout.braincode.xyz'
  company_name: 'Company Name'
  company_address: 'Company Address'
  admin_email: 'anton.rogachevskyi@braincode.xyz'
  product_url: 'http://dev.tenderscout.braincode.xyz'
  support: 'http://tenderscout.support.com'

  templates:
    supplier_invite: '8112615'
    sign_up_request: '7951598'
    sign_up_process: '7952090'

  uri:
    admin_sign_up: '/users/signup-requests'
    tender_details: ''

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default