default: &default
  from: 'anton.rogachevskyi@braincode.xyz'
  company_name: 'Company Name'
  company_address: 'Company Address'
  admin_email: 'anton.rogachevskyi@braincode.xyz'
  product_url: 'http://dev.tenderscout.braincode.xyz'
  support: 'http://tenderscout.support.com'
  tender_management_url: 'http://tender_management_url'
  api_url: 'http://api.dev.tenderscout.braincode.xyz'
  admin_url: 'http://admin.dev.tenderscout.braincode.xyz'
  templates:
    sign_up_request: '7951598'
    sign_up_process: '7952090'
    tender_publish: '8111794'
  uri:
    admin_sign_up: '/users/signup-requests'

development:
  <<: *default

staging:
  <<: *default

test:
  <<: *default

production:
  <<: *default